name: Build and push docker images


on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Set up metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mboilen/tgrgbox-web
          tags: |
            type=schedule
            type=ref,event=tag,prefix=v
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
      -
        name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


